// Generated by CoffeeScript 1.10.0
require.config({
  baseUrl: '../lib',
  paths: {
    underscore: 'underscore/underscore-min',
    jquery: 'jquery/dist/jquery.min',
    can: 'CanJS/amd/can',
    easyui: 'jquery-easyui/jquery.easyui.min',
    loading: 'jquery-loading/dist/jquery.loading.min',
    homeCtrl: '../public/js/HomeCtrl'
  }
});

require(['homeCtrl'], function(homeCtrl) {
  return new homeCtrl('body', {});
});
