// Generated by CoffeeScript 1.10.0
require.config({
  baseUrl: '../lib',
  paths: {
    _: 'underscore/underscore-min',
    $: 'jquery/dist/jquery.min',
    can: 'CanJS/amd/can',
    easyui: 'jquery-easyui/jquery.easyui.min',
    loading: 'jquery-loading/dist/jquery.loading.min',
    localStorage: '../public/js/servs/local-storage',
    Auth: '../public/js/servs/auth',
    homeCtrl: '../public/js/ctrls/HomeCtrl',
    loginCtrl: '../public/js/ctrls/LoginCtrl',
    clientManagementCtrl: '../public/js/ctrls/ClientManagementCtrl'
  },
  shim: {
    can: ['$'],
    loading: ['$'],
    easyui: ['$']
  }
});

require(['can', 'Auth'], function(can, Auth) {
  var Router, validRoute;
  validRoute = function(route, p) {
    if (!Auth.logined() && route !== 'login') {
      console.log('to login...');
      return window.location.hash = '!login';
    } else if (!route) {
      console.log("to home...");
      return window.location.hash = '!home';
    } else {
      return console.log("to " + route + "...");
    }
  };
  Router = can.Control({
    '{can.route} change': function(ev, attr, how, newVal, oldVal) {
      return validRoute(ev.route, 'change');
    },
    'login route': function(data) {
      return require(['loginCtrl'], function(loginCtrl) {
        return new loginCtrl('body', {});
      });
    },
    'logout route': function(data) {
      Auth.logout();
      return window.location.hash = '!login';
    },
    'route': function() {
      return validRoute('', 'empty');
    },
    'home route': function(data) {
      console.log('start home', data);
      return require(['homeCtrl'], function(homeCtrl) {
        return this.Home = new homeCtrl('body', {});
      });
    },
    'home/:id route': function(data) {
      console.log('child home', data);
      return require(['homeCtrl', 'clientManagementCtrl'], function(homeCtrl, clientManagementCtrl) {
        if (!this.Home) {
          this.Home = new homeCtrl('body', {});
        }
        switch (data.id) {
          case 'clientManagement':
            return this.current = new clientManagementCtrl('#currentWork', {});
          case 'userManagement':
            return this.current = '';
          case 'roleManagement':
            return this.current = '';
          case 'outReport':
            return this.current = '';
          case 'inReport':
            return this.current = '';
        }
      });
    }
  });
  new Router(window);
  return can.route.ready();
});
