// Generated by CoffeeScript 1.10.0
define(['can/control', 'can/view/mustache'], function(Control, can) {
  return Control.extend({
    init: function() {
      return this.element.html(can.view('../../public/view/home/home.html', {
        message: 'CanJS'
      }));
    }
  });
});
