// Generated by CoffeeScript 1.10.0
define(['can/control', 'can/view/mustache', 'Auth', '$'], function(Ctrl, can, Auth) {
  var mergeCol, onLoadSuccess;
  mergeCol = function(merge, colName) {
    return $('#clients').datagrid('mergeCells', {
      index: merge.index,
      field: colName,
      rowspan: merge.rowspan
    });
  };
  onLoadSuccess = function(data) {
    var i, k, merge, ref, results;
    results = [];
    for (i = k = 0, ref = data.length; k < ref; i = k += 1) {
      merge = data[i];
      mergeCol(merge, 'name');
      mergeCol(merge, 'address');
      results.push(mergeCol(merge, 'desc'));
    }
    return results;
  };
  return Ctrl.extend({
    init: function() {
      var mergeData;
      console.log(this.element);
      mergeData = [];
      this.element.html(can.view('../../public/view/home/client-management.html', {}));
      $('#mainLayout').layout();
      $('#contentLayout').layout();
      $('createClientDlg').dialog();
      $('#clients').datagrid({
        'loadFilter': function(ret) {
          var clientInfo, contractInfo, i, j, k, l, merge, ref, ref1, rets;
          rets = [];
          console.log(ret);
          for (i = k = 0, ref = ret.rows.length; k < ref; i = k += 1) {
            clientInfo = ret.rows[i];
            merge = {};
            if (clientInfo.contacts == null) {
              clientInfo.contacts = [];
            }
            if (clientInfo.contacts.length === 0) {
              rets.push(clientInfo);
            } else {
              mergeData.push({
                index: i,
                rowspan: clientInfo.contacts.length
              });
              for (j = l = 0, ref1 = clientInfo.contacts.length; l < ref1; j = l += 1) {
                contractInfo = clientInfo.contacts[j];
                rets.push({
                  name: clientInfo.name,
                  address: clientInfo.address,
                  contacts_name: contractInfo.name,
                  contacts_tel: contractInfo.tel,
                  contacts_email: contractInfo.email,
                  desc: clientInfo.desc
                });
              }
            }
          }
          return {
            total: rets.length,
            rows: rets
          };
        }
      });
      $('#clients').datagrid({
        'onLoadSuccess': function(data) {
          return onLoadSuccess(mergeData);
        }
      });
      return $.get(Auth.apiHost + 'mywms/client/page', function(data) {
        console.log(data);
        return $('#clients').datagrid({
          data: data
        });
      }).fail(function(data) {});
    },
    '#addClientBtn click': function() {
      return console.log('click');
    }
  });
});
