// Generated by CoffeeScript 1.10.0
define(['can/control', 'can/view/mustache', 'Auth', 'easyui', '_'], function(Control, can, Auth, easyui, un) {
  var appendChildMenu, appendMenu, data, genLeftMenu;
  data = new can.Map({
    username: ''
  });
  genLeftMenu = function(array) {
    return _.each(array, function(menu) {
      return appendMenu(menu);
    });
  };
  appendMenu = function(menu) {
    var isFirst;
    if (menu.level === 1) {
      $('#leftMenu').accordion('add', {
        title: menu.name,
        selected: isFirst
      });
    } else if (menu.level > 1 && menu.pid) {
      appendChildMenu(menu.pid, menu);
    }
    return isFirst = false;
  };
  appendChildMenu = function(fatherId, child) {
    var father;
    father = $('#leftMenu').accordion('getPanel', fatherId - 1);
    if (!father) {
      return;
    }
    return father.append(_.template('<a class="item " href=#!home/<%-url%>><p><b><%-name%></b></p></a>')(child));
  };
  return Control.extend({
    init: function() {
      var isFirst;
      this.element.html(can.view('../../public/view/home/home.html', data));
      $('#mainLayout').layout();
      $('#leftMenu').accordion();
      $('#tabs').tabs();
      data.attr('username', Auth.user().username);
      console.log(Auth.user());
      isFirst = true;
      return $.get(Auth.apiHost + 'mywms/main/menu', function(data, status) {
        console.log(data);
        if (parseInt(data.status) !== 0) {
          $.messager.alert('错误', '获取菜单失败 ' + data.message, 'error');
          return;
        }
        return genLeftMenu(data.data);
      }).fail(function() {});
    }
  });
});
