// Generated by CoffeeScript 1.10.0
define(['can/control', 'can/view/mustache', 'Auth'], function(Control, can, Auth) {
  var userInfo;
  if (Auth.logined()) {
    window.location.hash = '!home';
  }
  userInfo = new can.Map({
    username: 'admin',
    password: 'admin'
  });
  return Control.extend({
    init: function() {
      return this.element.html(can.view('../../public/view/login.html', userInfo));
    },
    '.login_button click': function() {
      return Auth.login(userInfo.attr());
    },
    '.reset_botton click': function() {
      userInfo.attr('username', '');
      return userInfo.attr('password', '');
    }
  });
});
