// Generated by CoffeeScript 1.10.0
define(['can', 'can/control', 'Auth', '_'], function(can, Control, Auth) {
  var contacts, i, j, userInfo;
  contacts = [];
  for (i = j = 0; j < 5; i = j += 1) {
    contacts.push({
      name: '',
      tel: '',
      email: ''
    });
  }
  userInfo = new can.Map({
    title: '新增客户',
    name: '',
    address: '',
    desc: '',
    contact1: contacts[0],
    contact2: contacts[1],
    contact3: contacts[2],
    contact4: contacts[3],
    contact5: contacts[4]
  });
  return Control.extend({
    init: function() {
      this.element.html(can.view('../../public/view/home/new-client.html', userInfo));
      $('#win').window({
        width: 600,
        height: 400,
        modal: true
      });
      $('#win').window('open');
      $('#save').unbind('click');
      return $('#save').bind('click', function() {
        var user;
        if (!$('#newClient').form('validate')) {
          $.messager.alert('提示', '请输入所有要求的内容！');
          return;
        }
        user = {};
        _.map(userInfo.attr(), function(it, key) {
          if (key === 'title') {
            return;
          }
          if (key.indexOf('contact') === 0) {
            if (user.contacts == null) {
              user.contacts = [];
            }
            if (it.name && it.tel && it.email) {
              return user.contacts.push(it);
            }
          } else {
            return user[key] = it;
          }
        });
        console.log(user);
        return $.postJSON(Auth.apiHost + 'mywms/client/create', user, function(data) {
          console.log(data);
          $('#win').window('close');
          return $.messager.alert('新增客户成功', '新增客户成功！');
        }, function(data) {
          return $.messager.alert('新增客户失败', data, 'error');
        });
      });
    }
  });
});
