// Generated by CoffeeScript 1.10.0
define(['localStorage', 'loading', 'easyui'], function(localStorage, loading, easyui) {
  var apiHost;
  apiHost = 'http://192.168.1.5:8080/';
  return {
    apiHost: apiHost,
    login: function(data) {
      $('html').loading({
        message: '正在登录...'
      });
      return $.post(apiHost + 'mywms/main/login', data, function(data, status) {
        $('html').loading('stop');
        if (parseInt(data.status) !== 0) {
          return $.messager.alert('登陆失败', data.message, 'error');
        } else {
          localStorage.set('logined', true);
          localStorage.set('user', data.data);
          return window.location.hash = '!home';
        }
      }).fail(function(data, status) {
        $('html').loading('stop');
        return $.messager.alert('登陆失败', 'http error:' + status + ' ' + data, 'error');
      });
    },
    logout: function() {
      localStorage.set('logined', false);
      return localStorage.remove('user');
    },
    logined: function() {
      return Boolean(localStorage.get('logined'));
    },
    user: function() {
      return localStorage.get('user');
    },
    createClient: function(userInfo) {
      return console.log(userInfo);
    }
  };
});
