// Generated by CoffeeScript 1.10.0
define(['_'], function(un) {
  return {
    set: function(key, value) {
      if (_.isObject(value)) {
        value = JSON.stringify(value);
      }
      return window.localStorage.setItem(key, value);
    },
    get: function(key) {
      var data, e, error;
      data = window.localStorage.getItem(key);
      try {
        data = JSON.parse(data);
      } catch (error) {
        e = error;
      }
      return data;
    },
    remove: function(key) {
      return window.localStorage.removeItem(key);
    }
  };
});
